### ISSUE TITLE
Dropdown list disabled after upgrade to 25.6

### ISSUE THREAD

**Issue by SuhovDE** [mc1arke/sonarqube-community-branch-plugin#1078]
After upgrading SonarQube server from **v25.5** to **v25.6**, the branch selection dropdown in the plugin UI stopped working. While the plugin worked flawlessly with v25.5, the dropdown no longer shows available branches or reacts to user input in v25.6.

### Affected Plugin Version

- **Plugin Version**: 1.24 (release)

### Affected SonarQube Version

- **Before Upgrade (Working)**: 25.5
- **After Upgrade (Broken)**: 25.6

### Expected Behavior

Branch dropdown should list all available branches for the current project and allow users to switch between them directly in the UI.

### Actual Behavior

- The dropdown is disable again.
- It is impossible to switch branches using the dropdown UI.
- However, navigation via:
  - **Background Tasks** page,
  - or manually appending `?branch=<branch_name>` to the URL,
  still works, which confirms that the branches exist and are accessible.

### Steps to Reproduce

1. Install plugin v1.24 on SonarQube 25.6.
2. Open a project dashboard.
3. Try to use the branch selection dropdown.

### Workarounds

- Use the **Background Tasks** page to navigate to branches.
- Manually append `?branch=<branch_name>` to the URL.

**Comment by riteshkumar-prive** [comment]
I'm observing the same issue but with version 25.5 and artefacts from 1.24 release.

Sonarqube version: v25.5.0.107428

Observations:
- The branch drop-down UI component was working as expected with UI artefacts from [PR](https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/1067) 
- I removed the `web` directory and re-deployed the artefacts from [1.24](https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.24.0/sonarqube-webapp.zip) release artefacts and it stopped working.

**Comment by GEownt** [comment]
I have the same problem but with other versions.
I am using the image provided by mc1arke `mc1arke/sonarqube-with-community-branch-plugin:25.4.0.105899-community`
I was running `sonarqube:25.4.0.105899-community` before and changing to mc1arke image doesn´t do anything to the dropdown, it still doesn´t work for me.
This is what my docker-compose.yml look like:
```
services:
  sonarqube:
    image: mc1arke/sonarqube-with-community-branch-plugin:25.4.0.105899-community
    restart: always
    environment:
      SONAR_JDBC_USERNAME: my_user
      SONAR_JDBC_PASSWORD: my_password
      SONAR_JDBC_URL: "my_database"
      SONAR_WEB_JAVAADDITIONALOPTS: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.24.0.jar=web"
      SONAR_CE_JAVAADDITIONALOPTS: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.24.0.jar=ce"
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dlog4j2.formatMsgNoLookups=true"
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
```
