### ISSUE TITLE
Unable to display the analyzed project's branch in the dropdown.

### ISSUE THREAD

**Issue by hilaltanriverdi** [mc1arke/sonarqube-community-branch-plugin#1088]
I understand that plugin version 25.5 is compatible with sonar version 25.5.x.
I have tried v25.5.0.107428 with v25.5.0 plugin but branch drop down is grayed out. 
Picking from background task or modifying url itself not working. Am I missing anything on setting/ setup?

**Comment by bihari-attila-nx** [comment]
Everything works fine with the latest versions in the .env file:
```
# The Sonarqube base image. 'latest' if building locally, '8.5-community' if targeting a specific version
SONARQUBE_VERSION=25.5.0.107428-community

# The name of the Dockerfile to run. 'Dockerfile' is building locally, 'release.Dockerfile' if building the release image
DOCKERFILE=Dockerfile

# The version of the plugin to include in the image
PLUGIN_VERSION=25.6.0-SNAPSHOT
```

**Comment by mcmontseny** [comment]
> I understand that plugin version 25.5 is compatible with sonar version 25.5.x. I have tried v25.5.0.107428 with v25.5.0 plugin but branch drop down is grayed out. Picking from background task or modifying url itself not working. Am I missing anything on setting/ setup?

Good afternoon!

Did you manage to get the dropdown enabled?

I’ll try to follow the configuration from the previous message.

**Comment by hilaltanriverdi** [comment]
> Everything works fine with the latest versions in the .env file:
> 
> ```
> # The Sonarqube base image. 'latest' if building locally, '8.5-community' if targeting a specific version
> SONARQUBE_VERSION=25.5.0.107428-community
> 
> # The name of the Dockerfile to run. 'Dockerfile' is building locally, 'release.Dockerfile' if building the release image
> DOCKERFILE=Dockerfile
> 
> # The version of the plugin to include in the image
> PLUGIN_VERSION=25.6.0-SNAPSHOT
> ```

there is no plugin version 25.6.0.  Latest version is 25.5.0 here https://github.com/mc1arke/sonarqube-community-branch-plugin/releases. and drop down is grayed out on latest

**Comment by xleon-seidor-es** [comment]
For me, it's the same issue. In my case, Sonarqube is installed by Helm inside Kubernetes.
I need to download the latest release plugin with the fix.

The issue was fixed following the right steps, as instructed by @martijnhae.
Thank you!

**Comment by martijnhaex** [comment]
Have the same setup as @xleon-seidor-es , Helm chart inside a Kubernetes. But didn't follow the README at first, missed the part of the init containers.

```
extraVolumes:
  - name: webapp
    emptyDir:
      sizeLimit: 50Mi

extraVolumeMounts:
  - name: webapp
    mountPath: /opt/sonarqube/web

extraInitContainers:
  - name: download-webapp
    image: busybox:1.37
    volumeMounts:
      - name: webapp
        mountPath: /web
    command:
      - sh
      - -c
      - wget -O /tmp/sonarqube-webapp.zip https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/25.5.0/sonarqube-webapp.zip &&
        unzip -o /tmp/sonarqube-webapp.zip -d /web &&
        chmod -R 755 /web &&
        chown -R 1000:0 /web &&
        rm -f /tmp/sonarqube-webapp.zip
```

After adding the above configuration, started working again (in version `25.6.0.109173`)
