### ISSUE TITLE
25.5.0 docker image failing to load

### ISSUE THREAD

**Issue by john-forrest** [mc1arke/sonarqube-community-branch-plugin#1089]
**Describe the bug**
I am trying to use the mc1arke/sonarqube-with-community-branch-plugin image off dockerhub,
replacing usage of the normal community sonarqube image, but it is failing to load - even if
I strip all the extra stuff I normally add.

**To Reproduce**

Previously I have a Dockerfile that added both the community branch plugin and the CXX C++ plugin to the community image. I've tried to use the sonarqube-with-community-branch-plugin image, so just adding the
CXX plugin but this fails to load with:

```
sonarqube-1  | 2025.06.10 22:02:58 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[WEB_SERVER] from [/opt/sonarqube]: /opt/java/openjdk/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -Xmx512m -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-25.5.0.jar=web -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-25.5.0.107428.jar:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.7.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process2899566363612429064properties
sonarqube-1  | Error opening zip file or JAR manifest missing : ./extensions/plugins/sonarqube-community-branch-plugin-25.5.0.jar
sonarqube-1  | Error occurred during initialization of VM
sonarqube-1  | agent library failed Agent_OnLoad: instrument
sonarqube-1  | 2025.06.10 22:02:58 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [Web Server]: 1
```

I ended up commenting all the extra from the Dockerfile so leaving:

ARG BASE=mc1arke/sonarqube-with-community-branch-plugin:latest
FROM $BASE

**Expected behavior**
Expect to come up

**Software Versions**
 - [25.5.0.107428-community](https://hub.docker.com/layers/mc1arke/sonarqube-with-community-branch-plugin/25.5.0.107428-community/images/sha256-49ed33475c00298fb10337615f876955876c10e8aac8cd9159db58ac0d005cee)
 - Docker: 26.1.3

**Comment by mc1arke** [comment]
Can you share the full contents of your dockerfile please, redacting any parts of commands that might be sensitive. I suspect you're in the wrong WORKDIR at the point the container starts, or that you've managed to overwrite the extensions directory, but I can't replicate the issue with the details you've provided.

**Comment by bernalvarela** [comment]
Good morning!!.

I'm using this docker compose config and i'm having the same problem.

```yml
services:
  sonarqube:
    image: mc1arke/sonarqube-with-community-branch-plugin:25.4.0.105899-community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:${POSTGRES_VERSION}
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sonarqube_data:
  sonarqube_logs:
  postgresql:
  postgresql_data:
```

```
sonarqube   | 2025.06.11 08:40:35 INFO  es[][o.e.c.s.ClusterApplierService] master node changed {previous [], current [{sonarqube}{OAs3qiHsS96R1YbUqqslhQ}{XVjJtVbYT2eHnydODJ5iLw}{sonarqube}{127.0.0.1}{127.0.0.1:40607}
{cdfhilmrstw}{8.16.3}{7000099-8518000}]}, term: 8, version: 29, reason: Publication{term=8, version=29}
sonarqube   | 2025.06.11 08:40:35 INFO  es[][o.e.c.c.NodeJoinExecutor] node-join: [{sonarqube}{OAs3qiHsS96R1YbUqqslhQ}{XVjJtVbYT2eHnydODJ5iLw}{sonarqube}{127.0.0.1}{127.0.0.1:40607}{cdfhilmrstw}{8.16.3}{7000099-851800
0}] with reason [completing election]
sonarqube   | 2025.06.11 08:40:35 INFO  es[][o.e.h.AbstractHttpServerTransport] publish_address {127.0.0.1:9001}, bound_addresses {127.0.0.1:9001}
sonarqube   | 2025.06.11 08:40:35 INFO  es[][o.e.n.Node] started {sonarqube}{OAs3qiHsS96R1YbUqqslhQ}{XVjJtVbYT2eHnydODJ5iLw}{sonarqube}{127.0.0.1}{127.0.0.1:40607}{cdfhilmrstw}{8.16.3}{7000099-8518000}{xpack.installed
=true, rack_id=sonarqube}
sonarqube   | 2025.06.11 08:40:35 INFO  es[][o.e.l.ClusterStateLicenseService] license [51bd13ec-5f92-48ad-afd5-82da5c6fcf7d] mode [basic] - valid
sonarqube   | 2025.06.11 08:40:35 INFO  es[][o.e.c.f.AbstractFileWatchingService] starting file watcher ...
sonarqube   | 2025.06.11 08:40:35 INFO  es[][o.e.c.f.AbstractFileWatchingService] file settings service up and running [tid=66]
sonarqube   | 2025.06.11 08:40:35 INFO  es[][o.e.r.s.FileSettingsService] setting file [/opt/sonarqube/temp/conf/es/operator/settings.json] not found, initializing [file_settings] as empty
sonarqube   | 2025.06.11 08:40:35 INFO  es[][o.e.g.GatewayService] recovered [0] indices into cluster_state
sonarqube   | 2025.06.11 08:40:35 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
sonarqube   | 2025.06.11 08:40:35 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[WEB_SERVER] from [/opt/sonarqube]: /opt/java/openjdk/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/op
t/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=
ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-ope
ns=jdk.management/com.sun.management.internal=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-25.4.0.jar=web -Dhttp.nonProxyHosts=localho
st|127.*|[::1] -cp ./lib/sonar-application-25.4.0.105899.jar:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.7.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process5336222922036685802properties
sonarqube   | Error opening zip file or JAR manifest missing : ./extensions/plugins/sonarqube-community-branch-plugin-25.4.0.jar
sonarqube   | Error occurred during initialization of VM
sonarqube   | agent library failed Agent_OnLoad: instrument
sonarqube   | 2025.06.11 08:40:35 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [Web Server]: 1
sonarqube   | 2025.06.11 08:40:35 INFO  app[][o.s.a.SchedulerImpl] Process[Web Server] is stopped
sonarqube   | 2025.06.11 08:40:35 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
sonarqube   | 2025.06.11 08:40:35 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 143
sonarqube   | 2025.06.11 08:40:35 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
sonarqube exited with code 0
```


Regards!!

**Comment by john-forrest** [comment]
My docker-compose is:

    version: "3"

    services:
      sonarqube:
        build:
          context: .
          dockerfile: Dockerfile
        #command: -Dsonar.ce.javaOpts=-Xmx512m -Dsonar.web.javaOpts=-Xmx512m '-Dsonar.search.javaOpts=-Xms1000m -Xmx1000m'
        command: -Dsonar.ce.javaOpts=-Xmx512m -Dsonar.web.javaOpts=-Xmx512m
        environment:
          - SONAR_JDBC_USERNAME=postgres
          - SONAR_JDBC_PASSWORD=****
          - SONAR_JDBC_URL=jdbc:postgresql://postgresql/postgres
          - SONAR_SEARCH_JAVAADDITIONALOPTS=-Dlog4j2.formatMsgNoLookups=true
        volumes:
          - /sonar-config:/opt/sonarqube/conf
          - /sonar-es:/opt/sonarqube/elasticsearch/config
        restart: unless-stopped
        networks:
          - sonarnet
        deploy:
          resources:
            limits:
              cpus: '1.50'
      nginx:
        build:
          context: .
          dockerfile: Dockerfile.nginx
        ports:
          - 9000:9000
    #      - 9092:9092
        volumes:
          - ./certs:/certshare
        restart: unless-stopped
        networks:
          - sonarnet
      postgresql:
        image: postgres:15
        environment:
          - POSTGRES_PASSWORD=****
          - PGDATA=/var/lib/postgresql/data/pgdata
    #      - POSTGRES_INITDB_ARGS=--auth-host=trust
        volumes:
          - /sonar-data:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
          - sonarnet

    networks:
      sonarnet:
        driver: bridge

**Comment by john-forrest** [comment]
Sorry I just saw you were after the Dockerfile not the compose. Will the minimum it failed with (we normally add some extra but I cut down to try) was:

    ARG BASE=mc1arke/sonarqube-with-community-branch-plugin:latest
    FROM $BASE

**Comment by mc1arke** [comment]
@john-forrest  thanks for this. Taking your docker-compose and Dockerfile, removing the NGingx configuration from your compose (I don't have the Dockerfile) an instead exposing Sonarqube port directly, I get a successful startup Sonarqube and am able to use it normally. Can you check you don't have anything unusual with cached images?

**Comment by mc1arke** [comment]
Although I do also wonder if there's anything unusual on any of your volumes. Do you get the same issue if you mount clean versions of your volumes?

**Comment by radokristof** [comment]
I'm using just the image, no modifications and I have the same problem.

**Comment by NathaanTFM** [comment]
Deleted my comment (do not delete the volume - we do not have the same configuration). It works for me - the only time I had problems booting was because of the /opt/sonarqube/data folder, but it doesn't seem related

**Comment by bernalvarela** [comment]
> Although I do also wonder if there's anything unusual on any of your volumes. Do you get the same issue if you mount clean versions of your volumes?

You are right!!, it was related with my volumes. I deleted them and it worked like a charm.

Thank you and regards!

**Comment by radokristof** [comment]
I have the same issue even if I remove all volumes.

**Comment by peteAhn** [comment]
Good issue, same here.

**Comment by mc1arke** [comment]
@radokristof I'd need your docker compose and dockerfile then - I can't replicate the issue with the details I've currently been provided. Any details you provide must be a minimal replication: I shouldn't need to configure certificates, proxies, external DNS etc

**Comment by radokristof** [comment]
@mc1arke current `docker-compose.yml`:

```
  sonarqube:
    depends_on:
      sonar-db:
        condition: service_healthy
    image: mc1arke/sonarqube-with-community-branch-plugin:latest
    container_name: sonarqube_app
    restart: always
    labels:
      caddy: sonarqube.example.com
      caddy.reverse_proxy: "{{ upstreams 9000 }}"
    networks:
      - sonarnet
      - caddy
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
#    volumes:
#      - ./volumes/sonarqube/app/conf:/opt/sonarqube/conf
#      - ./volumes/sonarqube/app/data:/opt/sonarqube/data
 ```

I use the image directly, so I don't have a `Dockerfile`
