### ISSUE TITLE
Error in Bamboo ~ To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required

### ISSUE THREAD

**Issue by KiraResari** [mc1arke/sonarqube-community-branch-plugin#173]
It was my impression that the point of this plugin was to enable branch analysis in the community edition of SonarQube. However, when I try to use the Sonar Gradle build step in Bamboo with Auto Branch enabled, even if I have the sonarqube-community-branch-plugin installed, I still get the following error message:

```
To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required. See https://redirect.sonarsource.com/doc/branches.html for more information.
```

I run SonarQube using the following docker-compose.yml:

```
version: "3"

services:
    sonarqube_7_9_3:
        image: sonarqube:7.9.3-community
        expose:
            - 9000
        ports:
            - "127.0.0.1:9000:9000"
        networks:
            - sonarnet
        environment:
            - sonar.jdbc.username=sonar
            - sonar.jdbc.password=sonar
            - sonar.jdbc.url=jdbc:postgresql://db_7_9_3/sonar
        volumes:
            - sonarqube_conf_7_9_3:/opt/sonarqube/conf
            - sonarqube_data_7_9_3:/opt/sonarqube/data
            - sonarqube_extensions_7_9_3:/opt/sonarqube/extensions
            - sonarqube_bundled-plugins_7_9_3:/opt/sonarqube/lib/bundled-plugins
            - sonarqube_common_7_9_3:/opt/sonarqube/lib/common

    db_7_9_3:
        image: postgres
        networks:
            - sonarnet
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
        volumes:
            - postgresql_7_9_3:/var/lib/postgresql
            - postgresql_data_7_9_3:/var/lib/postgresql/data

networks:
    sonarnet:

volumes:
    sonarqube_conf_7_9_3:
    sonarqube_data_7_9_3:
    sonarqube_extensions_7_9_3:
    sonarqube_bundled-plugins_7_9_3:
    sonarqube_common_7_9_3:
    postgresql_7_9_3:
    postgresql_data_7_9_3:
```

...and as stated in the documentation of the sonarqube-community-branch-plugin, I have added the plugin file `sonarqube-community-branch-plugin-1.3.0.jar` to the volumes. Or at least I think that's what I did. Since no detailed explanation was given, I simply researched where docker keeps its volumes and ubuntu, and then added the files to those places:

* `/var/lib/docker/volumes/sonarqube_sonarqube_common_7_9_3/sonarqube-community-branch-plugin-1.3.0.jar`
* `/var/lib/docker/volumes/sonarqube_sonarqube_extensions_7_9_3/plugins/sonarqube-community-branch-plugin-1.3.0.jar`

Even so, the error still occurs. Maybe I did something wrong, but I have no idea what.

Any help in resolving this would be greatly appreciated.

**Comment by mc1arke** [comment]
Your issue indicates the plugin isn't being initialized/executed properly. Can you confirm the plugin shows as installed in the update centre (if 'yes' then the file in lib/common is not being picked up, if 'no' then the version in extensions/plugins it not being picked up).

**Comment by mc1arke** [comment]
Closing since there's been no activity in 7 days. Feel free to re-open if you can provide further information or replication steps.

**Comment by Kira-Cesonia** [comment]
Sorry for the delay. It has been a busy week.

I now tried it with this docker-compose.yml:

```
version: "3"

services:
    sonarqube_7_9_3:
        image: sonarqube:7.9.3-community
        expose:
            - 9000
        ports:
            - "127.0.0.1:9000:9000"
        networks:
            - sonarnet
        environment:
            - sonar.jdbc.username=sonar
            - sonar.jdbc.password=sonar
            - sonar.jdbc.url=jdbc:postgresql://db_7_9_3/sonar
        volumes:
            - sonarqube_conf_7_9_3:/opt/sonarqube/conf
            - sonarqube_data_7_9_3:/opt/sonarqube/data
            - sonarqube_extensions_7_9_3:/opt/sonarqube/extensions
            - sonarqube_bundled-plugins_7_9_3:/opt/sonarqube/lib/bundled-plugins
            - sonarqube_common_7_9_3:/opt/sonarqube/lib/common
            - /home/ubuntu/sonarqube-community-branch-plugin-1.3.0.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar
            - /home/ubuntu/sonarqube-community-branch-plugin-1.3.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin.jar

    db_7_9_3:
        image: postgres
        networks:
            - sonarnet
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
        volumes:
            - postgresql_7_9_3:/var/lib/postgresql
            - postgresql_data_7_9_3:/var/lib/postgresql/data

networks:
    sonarnet:

volumes:
    sonarqube_conf_7_9_3:
    sonarqube_data_7_9_3:
    sonarqube_extensions_7_9_3:
    sonarqube_bundled-plugins_7_9_3:
    sonarqube_common_7_9_3:
    postgresql_7_9_3:
    postgresql_data_7_9_3:
```

This results in the plugin being put into the correct folders in the docker container, I checked. However, it does not appear in the list of installed plugins in the Marketplace, as the update center is now referred to.
