### ISSUE TITLE
Bitbucket Server ALM configuration fails (Http 404 for /api/alm_integrations/check_pat?almSetting=bitbucket  && /api/alm_integrations/set_pat)

### ISSUE THREAD

**Issue by benze** [mc1arke/sonarqube-community-branch-plugin#304]
I'm trying to run SonarQube 8.6.1 Community Edition Docker container with the 1.7.0-SNAPSHOT plugin from https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/301#issue-564436289.  However, when I try to configure a Bitbucket server, the configuration fails as the following API endpoints are not found:

```
HTTP Status 404 : /api/alm_integrations/check_pat?almSetting=bitbucket
HTTP Status 404 : /api/alm_integrations/set_pat
```

I tried to roll back to SonarQube 8.5-community docker container with the 1.6.0.jar plugin, but with the same error message.

Is there a special setting/configuration that I am missing in order to enable Bitbucket ALM integration with this plugin? 

*Steps to reproduce:*
- spin up container
```
docker-compose.yml
  sonar: 
    image: sonarqube:8.5-community
    ports:
      - "9000:9000"
    environment:
      TZ: America/Toronto
    volumes:
      - "./conf:/opt/sonarqube/conf"
      - "./logs:/opt/sonarqube/logs"
      - ./plugins/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar
      - ./plugins/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin.jar
```
- open network inspection tool in browser
- login as admin
- administration/ALM Integrations.  Configure a Bitbucket Server.  Add PAT token and save.
- click the `+` symbol, select Bitbucket server
- Try to enter PAT token.
- 404 visible for /api/alm_integrations/check_pat & /api/alm_integrations/set_pat endpoints

![image](https://user-images.githubusercontent.com/2797306/106693565-bf181300-65a4-11eb-9aa7-bb5da2e48cbb.png)

Unable to connect/authenticate to a Bitbucket server.

This occurs in both Sonar 8.5 and 8.6.  Has anyone been able to successfully connect/enable BB ALM integration?
