### ISSUE TITLE
Doc improvement

### ISSUE THREAD

**Issue by alkanna** [mc1arke/sonarqube-community-branch-plugin#346]
Hey, so I struggled for a few hours to get this to work, but it should be noted somewhere that this is a good starting template to get PR decorations to work with github actions :

```yml
name: SonarQube
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: Run sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            sonar-scanner \
              -Dsonar.pullrequest.provider=github \
              -Dsonar.pullrequest.branch="${{ github.event.pull_request.title }}" \
              -Dsonar.pullrequest.github.repository=${{ github.repository }} \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.pullrequest.key=${{ github.event.number }} \
              -Dsonar.pullrequest.base=${{ github.base_ref }}
          else
            sonar-scanner \
              -Dsonar.pullrequest.provider=github \
              -Dsonar.pullrequest.github.repository=${{ github.repository }} \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.branch.name=${GITHUB_REF##*/}
          fi
```
