### ISSUE TITLE
Branches disappear after restarting sonarqube deployment on openshift

### ISSUE THREAD

**Issue by gal12gal** [mc1arke/sonarqube-community-branch-plugin#347]
**Describe the bug**
After restarting the sonarqube application on openshift, with external DB, cant see branches in all projects.

**To Reproduce**
1.create a branch using the plugin 
2.scaled down the sonarqube deployment to 0 
3.scaled back to 1 
4. No branch to project other then master

**Expected behavior**
expected to see the branch after restarting the sonarqube app

**Software Versions**
 - SonarQube Version: . Version 8.4 (build 35506)
 - Plugin Version: 1.5.0

**Additional context**
made sure the plugin is indeed loaded and installed 
i dont know if its version related, should updating sonar / the plugin will work ?

**Comment by fgimenezm** [comment]
I have sonar 8.8-community with the 1.7.0 plugin running on openshift and I don't see that behavior.
I copied the plugin to the extensions PV and added a "subPath" mount to present the plugin also at the /opt/sonarqube/lib/common/ path which is not persistent:
```
          volumeMounts:
            - mountPath: /opt/sonarqube/data
              name: sonarqube-data
            - mountPath: /opt/sonarqube/extensions
              name: sonarqube-extensions
            - mountPath: /opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.7.0.jar
              name: sonarqube-extensions
              subPath: plugins/sonarqube-community-branch-plugin-1.7.0.jar
            - mountPath: /opt/sonarqube/logs
              name: sonarqube-logs
            - mountPath: /opt/sonarqube/temp
              name: sonarqube-temp
  ```
