### ISSUE TITLE
[GitLab] Merge request decoration only send summary message

### ISSUE THREAD

**Issue by kudaliar032** [mc1arke/sonarqube-community-branch-plugin#362]
Hi,

I have a problem, where merge request decoration on GitLab only sends the summary without sending in-line comments where the issue is found. When I checked the sonarqube logs I found the following message

```
...
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Console/Commands/RevokeAccessTokenCommand.php:29 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Providers/TelescopeServiceProvider.php:65 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Providers/TelescopeServiceProvider.php:19 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Providers/RouteServiceProvider.php:31 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Providers/AppServiceProvider.php:95 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Providers/AppServiceProvider.php:62 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Providers/AppServiceProvider.php:89 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Providers/AuthServiceProvider.php:111 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Providers/EventServiceProvider.php:33 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Models/Traits/Filterable.php:25 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Models/Traits/Filterable.php:27 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Models/Traits/Filterable.php:48 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/Exceptions/Handler.php:56 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Skipping app/helpers.php:22 since the commit does not belong to the MR
sonarqube_1  | 2021.05.25 15:55:48 INFO  ce[AXmkPLnkuYmAa0OtiKaf][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=SUCCESS | time=5132ms
sonarqube_1  | 2021.05.25 15:55:49 INFO  ce[AXmkPLnkuYmAa0OtiKaf][o.s.c.t.CeWorkerImpl] Executed task | project=php-node-cicd | type=REPORT | pullRequest=36 | id=AXmkPLnkuYmAa0OtiKaf | submitter=gitlab | status=SUCCESS | time=35064ms
...
```

Here is the configuration of the `.gitlab-ci.yml` that I use

```
sonarqube-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - master
    - develop
```

What caused that to happen? Was there any configuration missing? thank you
