### ISSUE TITLE
No MR decoration in GitLab after upgrade

### ISSUE THREAD

**Issue by p3k** [mc1arke/sonarqube-community-branch-plugin#412]
**Describe the bug**

After upgrading GitLab, Sonarqube and the plugin (details see below), no MR decorations are posted to GitLab, anymore.

While I can see in GitLab’s job log that code is analyzed, the MR decoration will neither be added to a new MR, nor updated for an existing one. It does not matter if the job / quality gate succeeds or fails.

**To Reproduce**

1. GitLab CI config

    ```yaml
    MR analysis:
      stage: test
      variables:
        SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
        GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
      cache:
        key: "${CI_JOB_NAME}"
        paths:
          - .sonar/cache
      interruptible: true
      script:
        # Defined below are properties for CI-specific settings only (CI variables etc.)
        # Further properties can be added to the `build.gradle` and `gradle.properties` files
        - ./gradlew sonarqube --info
          -Dorg.gradle.daemon=true
          -Dorg.gradle.jvmargs=-Xmx2g
          -Dsonar.css.stylelint.reportPaths=$WLT_STYLELINT_REPORT_PATH
          -Dsonar.gitlab.user_token=$GITLAB_AUTH_TOKEN
          -Dsonar.javascript.lcov.reportPaths=$WLT_COVERAGE_REPORT_PATH
          -Dsonar.login=$SONAR_AUTH_TOKEN
          -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
          -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
          -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID
      allow_failure: true
      only:
        - merge_requests
      tags:
        - sil-docker
    ```

2. Gradle config

    ```properties
    systemProp.sonar.host.url = https://sonar.host.dom
    systemProp.sonar.projectKey = group/project
    systemProp.sonar.projectName = Our Project
    systemProp.sonar.projectVersion = 1.0
    systemProp.sonar.qualitygate.wait = true
    ```

3. CI job log (excerpts)
   
    <details>
    <summary>Successful run</summary>

    ```
    > Task :sonarqube
    SCM writing changed lines
    SCM writing changed lines (done) | time=218ms
    Analysis report generated in 424ms, dir size=2 MB
    Analysis report compressed in 1680ms, zip size=1 MB
    Analysis report uploaded in 175ms
    ------------- Check Quality Gate status
    Waiting for the analysis report to be processed (max 300s)
    QUALITY GATE STATUS: PASSED - View details on https://sonar.host.dom/dashboard?id=project&pullRequest=2107
    Analysis total time: 5:09.024 s
    :sonarqube (Thread[Execution worker for ':',5,main]) completed. Took 5 mins 14.859 secs.
    Closing Git repo: /builds/portal/portal/.git
    BUILD SUCCESSFUL in 16m 25s
    17 actionable tasks: 17 executed
    Stopped 1 worker daemon(s).
    ```

    </details>

    <details>
    <summary>Failed run</summary>

    ```
    > Task :sonarqube
    SCM writing changed lines
    SCM writing changed lines (done) | time=829ms
    Analysis report generated in 1069ms, dir size=4 MB
    Analysis report compressed in 2164ms, zip size=2 MB
    Analysis report uploaded in 268ms
    ------------- Check Quality Gate status
    Waiting for the analysis report to be processed (max 300s)
    > Task :sonarqube FAILED
    :sonarqube (Thread[Execution worker for ':',5,main]) completed. Took 5 mins 36.749 secs.
    FAILURE: Build failed with an exception.
    * What went wrong:
    Execution failed for task ':sonarqube'.
    > QUALITY GATE STATUS: FAILED - View details on https://sonar.host.dom/dashboard?id=project&pullRequest=2107
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
    * Get more help at https://help.gradle.org
    BUILD FAILED in 10m 52s
    Closing Git repo: /builds/portal/portal/.git
    17 actionable tasks: 17 executed
    Stopped 1 worker daemon(s).
    ```

    </details>

**Expected behavior**
The plugin should add a comment to the corresponding MR as displayed in the screenshot below.

**Screenshots**

![image](https://user-images.githubusercontent.com/16631/128876332-10194c2b-8ce4-4158-9c79-e2ec227e64d8.png)

Note: This is what I see when I open the `Pull Request Decoration` settings in SonarQube. Is this correct because the community version does not come with this feature? Or should the plugin somehow populate this area?

![image](https://user-images.githubusercontent.com/16631/128871922-59e58b58-9d92-4662-b130-bc5bd0096fc2.png)

**Software Versions**
 - GitLab Version: 14.1.2 (community / self-hosted)
 - SonarQube Version: 8.9.2.46101 (community / self-hosted)
 - Plugin Version: 1.8.0
