### ISSUE TITLE
Version 1.10.0 not working with SonarQube 9.2.4

### ISSUE THREAD

**Issue by mastercard-rob** [mc1arke/sonarqube-community-branch-plugin#522]
**Describe the bug**
Have deployed SonarQube 9.2.4 using Helm and installed v1.10.0 of the plugin however when I scan a branch and pass the sonar.branch.name param to the sonarscanner I'm seeing the following message in the logs
java.lang.IllegalStateException: Current edition does not support branch feature

**To Reproduce**
1. Scan a project from Jenkins
2. Check the sonarqube server logs

**Expected behavior**
sonarscanner should pass 

**Screenshots**

**Software Versions**
 - SonarQube Version: Version 9.2.4 (build 50792)
 - Plugin Version: 1.10.0
 - 
**Additional context**
N/A

**Comment by mc1arke** [comment]
Which helm chart are you using, and how are you loading and configuring the plugin in it?

**Comment by FAE56** [comment]
Hi, I have same problem on **sonarque docker: 9.2.4.50792**

```
λ mvn clean verify sonar:sonar \
  -Dsonar.projectKey=demo \
  -Dsonar.branch.name=temp \
  -Dsonar.host.url=http://virtual:9000 \
  -Dsonar.login=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

```
sonarqube_1  | 2021.12.31 07:37:04 ERROR web[AX4PayOKbUWIT3OOAAA0][o.s.s.w.WebServiceEngine] Fail to process request http://virtual:9000/api/ce/submit?projectKey=demo&projectName=demo&characteristic=branch%3Dtemp&characteristic=branchType%3DBRANCH
sonarqube_1  | java.lang.IllegalStateException: Current edition does not support branch feature
sonarqube_1  |  at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
sonarqube_1  |  at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:59)
sonarqube_1  |  at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:82)
sonarqube_1  |  at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:100)
sonarqube_1  |  at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:111)
```

In addition, below properties seem to be useless

```
# cat sonar.properties |grep "sonarqube-community-branch-plugin"
sonar.web.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=ce
```

```
# ls /opt/sonarqube/extensions/plugins/
README.txt                                    sonar-pmd-plugin-3.3.1.jar
sonar-findbugs-plugin-4.0.5.jar               sonarqube-community-branch-plugin-1.10.0.jar
sonar-l10n-zh-plugin-9.2.jar
```

```
λ cat docker-compose.yml
version: "3.7"

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
```
