### ISSUE TITLE
[Azure DevOps] No detection for azure devops integration

### ISSUE THREAD

**Issue by LvffY** [mc1arke/sonarqube-community-branch-plugin#596]
**Describe the bug**

I recently find that our Azure DevOps projects are no more detected as Azure DevOps projets and so the default branch is not parsed correctly.

When we start using Sonarqube and this plugin, we use to analyze our projects with the project key : `$(System.TeamProject)_$(Build.Repository.Name)`. This key was once enough to sonarqube be able to detect that my project is an Azure DevOps project. 

Previously, I was able to infer this behavior by manually importing my Azure DevOps project in Sonarqube and see the project key. Now, when I'm importing a project from Azure DevOps I see that the project key is `$(System.TeamProject)_$(Build.Repository.Name)_ARandomString`. I think this issue comes from here.

Is there anything I'm missing ? 

**To Reproduce**
1. Analyze your code

```yaml
- task: SonarQubePrepare@5
  displayName: 'Prepare SonarQube'
  inputs:
    SonarQube: ${{ parameters.sonarqube_connection_name }}
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=$(System.TeamProject)_$(Build.Repository.Name)

- task: Maven@3
  displayName: 'Run Sonar analysis'
  inputs:
    options: "-Dsonar.branch.name=$(SONAR_BRANCH)"
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    goals: sonar:sonar

- task: SonarQubePublish@5
  displayName: 'Publish sonarqube analysis'
  inputs:
    pollingTimeoutSec: '300'
  condition: succeededOrFailed()
```

2. Go to your project and check the project key. Your default branch should be **master**, withtout any regards of your real default branch and the DevOps integration should not be enabled.

     
       You could compare to a manual import, where your default branch should be the right default branch and, of course, the devops integration should be enabled.

**Expected behavior**

My sonarqube project should detect the Azure DevOps integration based on the project key (or any other specified pattern/conf)

**Software Versions**
 - SonarQube Version: `Version 9.4 (build 54424)`
 - Plugin Version: `1.11.0` also found in `1.10.0`
