### ISSUE TITLE
Gitlab tag seen as branch

### ISSUE THREAD

**Issue by obriat** [mc1arke/sonarqube-community-branch-plugin#678]
**Describe the bug**
I try to add projectVersion based on git tag that triggers SonarQube via gitlab-ci, but it creates a branch in SonarQube. Although the version is created, Sonar shows it on the new branch not on the tagged one.

Maybe I miss something but I could not find help in the documentation (Sonar or this plug-in).

**To Reproduce**
1. Create a gitlab-ci task triggered by $CI_COMMIT_TAG that executes sonarsource/sonar-scanner-cli:latest docker container with option `-Dsonar.projectVersion=$CI_COMMIT_TAG`
2. Tag a branch : X.Y.Z
3. Wait for CI to execute task
4. Notice on SonarQube that a new branch name X.Y.Z is visible (marked with the correct X.Y.Z version)

**Expected behavior**
No new branch should be created on SonarQube, and the version should be created on the tagged branch.

**Details**
gitlab-ci.yml
```
  rules:
    - if: '($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event")'
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - sonar-scanner -Dsonar.projectVersion=$CI_COMMIT_TAG
```

logs extracts
```
Checking out 28714ce1 as 0.0.1...
INFO: Auto detected BRANCH configuration with source 0.0.1 using com.github.mc1arke.sonarqube.plugin.scanner.autoconfiguration.GitlabCiAutoConfigurer
INFO: Branch name: 0.0.1
```

**Software Versions**
- OS: Debian 11.5
- SonarQube : 9.6.1 (build 59531)
- Plugin version: 1.12.0
- Java : openjdk 11.0.16 2022-07-19
- Nginx (reverse proxy with tls) : 1.18.0

**Comment by obriat** [comment]
Ok, I found the error, I remove the following lines int  `sonar.properties` :
```
  sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=ce
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=web
```

**Comment by MCMicS** [comment]
sounds like that the sonar scanner will detect the tag as branch name an set the needed varaible.
you can try to add the `sonar.branch.name` manually for Tag build

or maybe this could work if you want to tag always main branch:  `sonar-scanner -Dsonar.projectVersion=$CI_COMMIT_TAG -Dsonar.branch.name=$CI_DEFAULT_BRANCH`

see also following topic which shows that the default branch name should set to `$CI_COMMIT_REF_NAME`, But this sounds that the Commit ref is not the branch from which the tag was created. Maybe you echo out the content of this variable.
- https://community.sonarsource.com/t/no-version-entries-when-using-gitlab-ci-magic/53614

**Comment by obriat** [comment]
Thanks it works, but it tags the default branch not the tagged one.

I think its due to "CI_COMMIT_BRANCH he  commit branch name. Available in branch pipelines, including pipelines  for the default branch. **Not available in merge request pipelines or tag  pipelines**" https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

**Comment by MCMicS** [comment]
Have you checked the $CI_COMMIT_REF_NAME variable or printed out all env variables to check?

**Comment by obriat** [comment]
I'll give it a try thanks

**Comment by obriat** [comment]
$CI_COMMIT_REF_NAME refers to the tag name, none the other Gitlab variables displayed with debug mode refer to the tagged branch. The job web page display "Pipeline #{XXXXX} for {tag_name}.

I'll try to get the tagged branch via a git command, e.g. : `git branch -r --contains HEAD | sed -e '1!d' -e 's/.*origin\///'`

**Comment by obriat** [comment]
I cannot retrieve the tag from git commands, at best I managed to retrieve gitlab spcific branch: `git show -s --pretty=%d HEAD => HEAD, refs/pipelines/12345` .
So the problem is on gitlab side: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26548

**Comment by obriat** [comment]
I had to add the `GIT_DEPTH: 0` variable to solve another problem, so I run again some git commands and I manage get the  tagged branch with the following command: 
`git branch --remote --verbose --no-abbrev --contains | sed -rne 's/^[^\/]*\/([^\ ]+).*$/\1/p'` 
Now I have to use it with `-Dsonar.branch.name=` 

Hope it helps...

**Comment by obriat** [comment]
It's ugly but it works:
```
  variables:
    # Avoid Sonar's "shallow clone" warning
    GIT_DEPTH: 0
  before_script:
    # Use git because Gitlab could not provide tagged branch variable
    # @see https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/678
    - if [ "${CI_COMMIT_TAG}" ]; then SONAR_OPTIONS="-Dsonar.projectVersion=$CI_COMMIT_TAG -Dsonar.branch.name=$(git branch --remote --verbose --no-abbrev --contains | sed -rne 's/^[^\/]*\/([^\ ]+).*$/\1/p')"; else SONAR_OPTIONS=""; fi
  script:
    - sonar-scanner ${SONAR_OPTIONS}
```
