### ISSUE TITLE
README for helm installation is outdated

### ISSUE THREAD

**Issue by AmitBaranes** [mc1arke/sonarqube-community-branch-plugin#713]
**Describe the bug**
README file mention old path which no longer exists.

**To Reproduce**
1. Install the plugin using the README instructions.

**Screenshots**
Error opening zip file or JAR manifest missing : /opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.14.0.jar/sonarqube-community-branch-plugin-1.14.0.jar

**Software Versions**
 - SonarQube Version: 9.8
 - Plugin Version: 1.14
 - 
**Additional context**

README should be updated to :

## Kubernetes with official Helm Chart

When using
[Sonarqube official Helm Chart](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube),
you need to add the following settings to your helm values, where `${version}` should be replaced with the plugin
version (e.g. `1.14.0`):

```yaml
plugins:
  install:
    - https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/${version}/sonarqube-community-branch-plugin-${version}.jar
  lib:
    - sonarqube-community-branch-plugin-${version}.jar
jvmOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-${version}.jar=web"
jvmCeOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-${version}.jar=ce"
```
`/opt/sonarqube/extensions/plugins` is the new path, regardless the `persistence.enabled=true`.

Sonarqube official helm usage of above path - https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/deployment.yaml#L117
