### ISSUE TITLE
Documentation is not clear on how to install on docker-composed Sonarqube instances

### ISSUE THREAD

**Issue by KrappRamiro** [mc1arke/sonarqube-community-branch-plugin#859]
Hi! Im a newbie developer, and im trying to use your plugin, but i can't understand how to install it.

Im using this docker-compose.yaml for Sonarqube

 ```yaml
version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "8087:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
```

I have 3 options

1. Copying the `.jar` file into the sonarqube_extension volumes
2. Use the Dockerfile provided (i dont get how, I'm supposed to modify my docker-compose ?)
3. Use the docker-compose provided (i dont get how also)

I dont understand which one i should use in my case.

Thanks!
