### ISSUE TITLE
Plugin 1.18 not Uploading Report with 10.3

### ISSUE THREAD

**Issue by zunera-aion** [mc1arke/sonarqube-community-branch-plugin#883]
**Describe the bug**
Unable to upload report from Azure DevOps to the SonarQube. SonarAnalyze@5 fails at report upload.

**To Reproduce**
This is the docker-compose file I used
````
version: "3"

services:
  sonarqube:
    image: sonarqube:10.3-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube1_data:/opt/sonarqube/data
      - sonarqube1_extensions:/opt/sonarqube/extensions
      - sonarqube1_logs:/opt/sonarqube/logs
      - /root/sonarqube/plugins/sonarqube-community-branch-plugin-1.18.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.18.0.jar
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql1:/var/lib/postgresql
      - postgresql1_data:/var/lib/postgresql/data

volumes:
  sonarqube1_data:
  sonarqube1_extensions:
  sonarqube1_logs:
  postgresql1:
  postgresql1_data:
````

**Expected behavior**
The reports should be uploaded successfully.

**Screenshots**
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/97824388/85d7daef-578e-4ab2-b01e-07a8eaf0f170)

**Software Versions**
 - SonarQube Version: [10.3]
 - Plugin Version: [1.18]

**Additional context**
I have tried adding branch name to sonar additional properties
I have also tried using the Default branch name set to my branch name in SQ settings.

**Comment by mc1arke** [comment]
If you're using the Sonarqube docker image rather than the one with the plugin embedded then you'll need to ensure you're setting `SONAR_WEB_JAVAADDITIONALOPTS` and `SONAR_CE_JAVAADDITIONALOPTS` in the container environment, e.g.

```
...
services:
  sonarqube:
    image: sonarqube:10.3-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_WEB_JAVAADDITIONALOPTS: "-javaagent:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.18.0.jar=web"
      SONAR_CE_JAVAADDITIONALOPTS: "-javaagent:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.18.0.jar=ce"
    volumes:
      - sonarqube1_data:/opt/sonarqube/data
      - sonarqube1_extensions:/opt/sonarqube/extensions
      - sonarqube1_logs:/opt/sonarqube/logs
      - /root/sonarqube/plugins/sonarqube-community-branch-plugin-1.18.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.18.0.jar
...
```
