### ISSUE TITLE
Inline comments not appearing on the 'Files Changed' tab in GitHub using GitHub workflows

### ISSUE THREAD

**Issue by JordanR-img** [mc1arke/sonarqube-community-branch-plugin#920]
Hi Michael,

Firstly, thank you for providing this plugin and the time and effort you have put into this!

We have been having an issue while using your plugin, it seems that inline comments on GitHub are not being populated in the files changed tab. (Though we're still receiving the SonarQube summary)

This has worked in the past when we have used the same version of the plugin (SonarQube 9.9.2 LTS and 1.14.0 Community Branch Plugin) but were using the ADO tasks (sonarqubePrepare@5, sonarqubePublish@5). The code being stored in GitHub whilst the pipeline was in ADO, this populated the comments in GitHub and worked as it should.

Upon moving to GitHub workflows and connecting to SonarQube via a GitHub app, the comments are not being populated on GitHub. We have tested this with

- SonarQube 10.3 with community branch plugin 1.18.0
- SonarQube 10.4 with community branch plugin 1.19.0

We are following the manual install steps that you specify in your readme

Is this expected behaviour? Is there something we could possibly be missing when moving to GitHub workflows?

**Comment by JordanR-img** [comment]
@mc1arke Hello Michael, have you had a bit of time to look over this one?

**Comment by mc1arke** [comment]
Without a (simplified) copy of your build scripts, or detailed replication steps, it's impossible to diagnose this. I suspect your Github workflow is performing a rebase/merge as part of check-out so is reporting a different commit ID into Sonarqube than the one present in Github and the decoration is therefore being attempted against a commit that doesn't exist on the source branch, but without further details it's purely guesswork.

**Comment by JordanR-img** [comment]
Hi @mc1arke 
Reproducing the bug with inline comments with SonarQube to GitHub when using GitHub workflows to execute the scanning

### **Use a SonarQube GitHub app for connection between SonarQube and GitHub**

**Configure the permissions and events tab in configuration of the SonarQube GitHub app like so below**

- Repository Permissions:
Checks: Read and Write
Commit Statuses: Read-only
Contents: Read-only
Metadata: Read-only
Pull Requests: Read and Write

- Organization Permissions
Members: Read-only
Projects: Read-only

- Account Permissions
Email addresses: Read-only

### **Create project in SonarQube**
**In DevOps Platform Integration Settings:**
- Configuration name: (Name of SonarQube GitHub app connection)
- Repository name: (ORG/REPO-NAME)
- Enable analysis summary under the GitHub conversation tab (Make sure this is turned on)

### **Setup GitHub workflow**

- Run the SonarQube scan action
```
- name: SonarQube Scan
- uses: sonarsource/sonarqube-scan-action@master
```
Run the quality gate check
```
name: Sonarqube Quality Gate Check
uses: sonarsource/sonarqube-quality-gate-action@master
```

Extra notes:
- The workflow that executes the above actions is triggered on creation of PR
- Quality gate sends results to PR but the inline comments on the files change tab do not appear

Question:
We have seen the inline comments working with ADO pipelines + GitHub repos, but have never been able to get it working with GitHub workflows + GitHub repos - do you have this working?

**Comment by adrianmusante** [comment]
@JordanR-img maybe is related to #937.

I think that `sonarsource/sonarqube-quality-gate-action` is not necessary if you have associated project to repository because SonarQube app decorate PR in background from Compute Engine.

![image](https://github.com/user-attachments/assets/3ad3941f-188d-413f-b2e0-a5416b622c23)
 
These are two GitHub workflows that I use and that works for me. Hopefully, this can help you solve the problem.

- **Maven**

```yaml
name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'Makefile'
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened]

env:
  JAVA_VERSION: 21
  SONAR_JAVA_VERSION: 17
  SONAR_PLUGIN: org.sonarsource.scanner.maven:sonar-maven-plugin
  JACOCO_PLUGIN: org.jacoco:jacoco-maven-plugin:0.8.12

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube metadata
        id: sonar
        run: |
          echo "project-key=${GITHUB_REPOSITORY/\//_}" >> $GITHUB_OUTPUT
          echo "project-name=${GITHUB_REPOSITORY}" >> $GITHUB_OUTPUT

      - name: SonarQube arguments
        id: sonar-args
        run: |
          sonar_args=("-Dsonar.projectKey=${{steps.sonar.outputs.project-key}}" "-Dsonar.projectName=${{steps.sonar.outputs.project-name}}")
          if [ "${{github.event_name}}" = "pull_request" ]; then
            sonar_args+=("-Dsonar.scm.revision=${{github.event.pull_request.head.sha}}")
            sonar_args+=("-Dsonar.pullrequest.key=${{github.event.number}}")
            sonar_args+=("-Dsonar.pullrequest.branch=${{github.head_ref}}" "-Dsonar.pullrequest.base=${{github.base_ref}}")
          fi
          echo "args=${sonar_args[*]}" >> $GITHUB_OUTPUT

      - name: Compile
        run: mvn -B clean compile

      - name: Build and analyze
        if: ${{ fromJson(env.JAVA_VERSION) >= fromJson(env.SONAR_JAVA_VERSION) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B $JACOCO_PLUGIN:prepare-agent verify $JACOCO_PLUGIN:report \
            $SONAR_PLUGIN:sonar ${{ steps.sonar-args.outputs.args }}

      - name: Test
        if: ${{ fromJson(env.JAVA_VERSION) < fromJson(env.SONAR_JAVA_VERSION) }}
        run: mvn -B $JACOCO_PLUGIN:prepare-agent verify $JACOCO_PLUGIN:report
      - name: Set up JDK ${{ env.SONAR_JAVA_VERSION }}
        if: ${{ fromJson(env.JAVA_VERSION) < fromJson(env.SONAR_JAVA_VERSION) }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.SONAR_JAVA_VERSION }}
      - name: SonarQube analysis
        if: ${{ fromJson(env.JAVA_VERSION) < fromJson(env.SONAR_JAVA_VERSION) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B $SONAR_PLUGIN:sonar ${{ steps.sonar-args.outputs.args }}
```

- **sonarqube-scan-action**

```yaml
name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'Makefile'
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube metadata
        id: sonar
        run: |
          echo "project-key=${GITHUB_REPOSITORY/\//_}" >> $GITHUB_OUTPUT
          echo "project-name=${GITHUB_REPOSITORY}" >> $GITHUB_OUTPUT

      - name: SonarQube arguments
        id: sonar-args
        run: |
          sonar_args=("-Dsonar.projectKey=${{steps.sonar.outputs.project-key}}" "-Dsonar.projectName=${{steps.sonar.outputs.project-name}}")
          if [ "${{github.event_name}}" = "pull_request" ]; then
            sonar_args+=("-Dsonar.scm.revision=${{github.event.pull_request.head.sha}}")
            sonar_args+=("-Dsonar.pullrequest.key=${{github.event.number}}")
            sonar_args+=("-Dsonar.pullrequest.branch=${{github.head_ref}}" "-Dsonar.pullrequest.base=${{github.base_ref}}")
          fi
          echo "args=${sonar_args[*]}" >> $GITHUB_OUTPUT

      - name: Build and analyze
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: ${{ steps.sonar-args.outputs.args }}

```
