### ISSUE TITLE
{"errors":[{"msg":"Current edition does not support branch feature"}]}

### ISSUE THREAD

**Issue by coderguy1998** [mc1arke/sonarqube-community-branch-plugin#960]
**Describe the bug**
I'm using Jenkins Multibranch pipeline along with Sonarqube 10.6, I have installed 1.21 version of this plugin and it is appearing under the marketplace's installed plugin's screen. But after the analysis is done, it is not able to post the result to sonarqube with the error mentioned. {"errors":[{"msg":"Current edition does not support branch feature"}]}

Failed to upload report: Error 500 on http://X.X.X.X:6030/api/ce/submit?projectKey=_execution-venue-backend_67a38177-3108-46ba-bbac-9c519&projectName=execution-venue-backend&characteristic=branch%3Dmain&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"Current edition does not support branch feature"}]} -> [Help 1]

**Expected behavior**

**Screenshots**
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/8350d298-7285-4b91-a97d-6f8d449b54fd">

**Software Versions**
 - SonarQube Version: [e.g. Version 10.6]
 - Plugin Version: [e.g. 1.21.0]

**Additional context**

**Comment by chwehrli** [comment]
Had the same issue...
sonarqube v10.6 installed on k8s via Helm chart 10.6.1+3163 (https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube)

In my case it was .Values.sonarProperties.**sonar.ce.javaOpts**  overwriting .Values.jvmCeOpts

According to the chart jvmOpts and jvmCeOpts anyway got deprecated - see:
https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/values.yaml#L412-L416

so better to use sonar.web.javaOpts and sonar.ce.javaOpts directly instead.

**Comment by coderguy1998** [comment]
I'm using docker-compose 

```
sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_WEB_JAVAADDITIONALOPTS=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.21.0.jar=web
      - SONAR_CE_JAVAADDITIONALOPTS=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.21.0.jar=ce
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
```

**Comment by coderguy1998** [comment]
Thanks

**Comment by rickjames961** [comment]
Can anyone provide a snippet and show exactly where sonar.web.javaOpts and sonar.ce.javaOpts should be set?  i have tried every way i can think of and im still gettting the message {"errors":[{"msg":"Current edition does not support branch feature"}]}. 
Sonarqube 10.6 deployed on AKS with helm chart 

sonar.web.javaOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=web"
sonar.ce.javaOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=ce"

**Comment by rickjames961** [comment]
Let me save someone else the time...It goes under sonarProperties to be injected in a custom sonar.properties file
```
# A custom sonar.properties file can be provided via dictionary.
# For example:
sonarProperties:
  sonar.web.javaOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=web"
  sonar.ce.javaOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=ce"
```
  
```
  kubectl exec -it sonarqube-sonarqube-0 -- /bin/sh
Defaulted container "sonarqube" out of: sonarqube, init-sysctl (init), concat-properties (init), install-plugins (init)
$ cd conf
$ ls
sonar.properties
$ more sonar.properties
sonar.ce.javaOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=ce
sonar.web.javaOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=web
```
