### ISSUE TITLE
Current edition does not support branch feature

### ISSUE THREAD

**Issue by Stormrice** [mc1arke/sonarqube-community-branch-plugin#968]
**Describe the bug**
We did check the other threads mentioning this error, but no answer has helped us.

Hello, we are using Gitlab Runner with Sonarqube and try to use your plugin. Unfortunately, Sonarqube is throwing this error:
```
Caused by: org.sonarqube.ws.client.HttpException: Error 500 on https://name.example.com/api/ce/submit?projectKey=xxx&characteristic=branch%3Ddevops&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"Current edition does not support branch feature"}]}
```

**To Reproduce**
We use the official 10.6-community docker image, with the required options:

```
  ct-sonarqube:
    image: sonarqube:10.6.0-community
    container_name: ct-sonarqube
    hostname: ct-sonarqube
    restart: always
    links:
      - ct-postgres
    environment:
      ...
      SONAR_WEB_JAVAADDITIONALOPTS: -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=web
      SONAR_CE_JAVAADDITIONALOPTS: -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=ce
      ...
```

We did put the 1.22.0 .jar file to `/opt/sonarqube/extensions/plugins/`.

And restarted the container. No error shows up in docker logs, Sonarqube is operational.

We did validate the warning for using a third-party plugin.

The Server base URL option is set to: `https://name.example.com`

Here is the call in the CI script:
```
    - dotnet sonarscanner begin /k:xxx /d:sonar.token=$SONAR_TOKEN /d:sonar.host.url=$SONAR_HOST_URL /d:sonar.scanner.skipJreProvisioning=true
    - nuget restore ...
    - dotnet build -c Release /nodereuse:false ...
    - dotnet sonarscanner end /d:sonar.token=$SONAR_TOKEN
```

We have added the project into Sonarqube using Gitlab import before running the Gitlab CI.

**Expected behavior**
This plugin to recognize the Gitlab CI branch and not throwing the exception above.

**Screenshots**
![image](https://github.com/user-attachments/assets/30bfd889-38c4-4f7b-be9f-8610bff89a87)

**Software Versions**
 - SonarQube Version: 10.6 Community
 - Plugin Version: Release 1.22.0

**Additional context**
N/A
